### ISSUE TITLE
1.5.2.1 issue

### ISSUE THREAD

**Issue by MHSF** [nemesis-software/nemesis-support#19]
трябва да се обърнем към немезис
https://repository.nemesis.io/artifactory/plugins-snapshot/com/nemesis/platform/1.5.2.1.BUILD-SNAPSHOT/maven-metadata.xml
errors 
0 
status 404
message "Maven metadata not found for 'com/nemesis/platform/1.5.2.1.BUILD-SNAPSHOT/maven-metadata.xml'."

**Comment by MHSF** [comment]
Log info: [WARNING] Could not transfer metadata com.paypal.sdk:paypal-core/maven-metadata.xml from/to sonatype-nexus-staging (https://oss.sonatype.org/service/local/staging/deploy/maven2/): Not authorized , ReasonPhrase:Unauthorized.
[WARNING] Failure to transfer com.paypal.sdk:paypal-core/maven-metadata.xml from https://oss.sonatype.org/service/local/staging/deploy/maven2/ was cached in the local repository, resolution will not be reattempted until the update interval of sonatype-nexus-staging has elapsed or updates are forced. Original error: Could not transfer metadata com.paypal.sdk:paypal-core/maven-metadata.xml from/to sonatype-nexus-staging (https://oss.sonatype.org/service/local/staging/deploy/maven2/): Not authorized , ReasonPhrase:Unauthorized.

**Comment by gochev** [comment]
Здравейте,
не са следвани стъпките описани на главната страница, така, че няма как да ви помогнем ако желаете in house помощ, моля обърнете се за consulting.

Цитирам стъпките отново:
_Each issue should be submited with detailed information in order to be fixed. This information includes:_

_- Steps to reproduce from start.nemesis.io generated project, including the version you are using._
_- Unit test showing the the issue, and showing the expected behaviour._

2рата част разбира се в случая няма как да я изпълните, но поне направете първата.

Ако трябва да гадая:
или ви липсва settings.xml за достъп до нашето репозитори на машината на която изпълнявате.
или имате unreliable интернет, който явно е спрял или спира.
опитайте отново build-a с -U, когато имате интернет и settings.xml файл

**Comment by gochev** [comment]
close-вам проблема, тъй като бях информиран, че се е оправил магически вероятно след като се е оправил магически и интернета.
